if Author.all.blank?
  mx = Author.create first_name: "Malcolm", last_name: "X",photo_id:"http://i854.photobucket.com/albums/ab108/The_Big_Zukini/malcolmx.jpg", bio: "Born on May 19, 1925, in Omaha, Nebraska, Malcolm X was a prominent black nationalist leader who served as a spokesman for the Nation of Islam during the 1950s and '60s. Due largely to his efforts, the Nation of Islam grew from a mere 400 members at the time he was released from prison in 1952 to 40,000 members by 1960. Articulate, passionate and a naturally gifted and inspirational orator, Malcolm X exhorted blacks to cast off the shackles of racism by any means necessary, including violence. The fiery civil rights leader broke with the group shortly before his assassination, February 21, 1965, at the Audubon Ballroom in Manhattan, where he had been preparing to deliver a speech."
  kh = Author.create first_name: "Khaled", last_name: "Hosseini",photo_id:"http://i854.photobucket.com/albums/ab108/The_Big_Zukini/khosseini.jpg", bio:"Khaled Hosseini was born in Kabul, Afghanistan, in 1965. His father was a diplomat in the Afghan Foreign Ministry and his mother taught Farsi and history at a high school in Kabul. In 1976, the Foreign Ministry relocated the Hosseini family to Paris. They were ready to return to Kabul in 1980, but by then their homeland had witnessed a bloody communist coup and the invasion of the Soviet Army. The Hosseinis sought and were granted political asylum in the United States, and in September 1980 moved to San Jose, California. Hosseini graduated from high school in 1984 and enrolled at Santa Clara University, where he earned a bachelor’s degree in biology in 1988. The following year he entered the University of California, San Diego, School of Medicine, where he earned a medical degree in 1993. He completed his residency at Cedars-Sinai medical center in Los Angeles and was a practicing internist between 1996 and 2004.n March 2001, while practicing medicine, Hosseini began writing his first novel, The Kite Runner. Published by Riverhead Books in 2003, that debut went on to become an international bestseller and beloved classic, sold in at least seventy countries and spending more than a hundred weeks on the New York Times bestseller list. In May 2007, his second novel, A Thousand Splendid Suns, debuted at #1 on the New York Times bestseller list, remaining in that spot for fifteen weeks and nearly an entire year on the bestseller list. Together, the two books have sold more than 10 million copies in the United States and more than 38 million copies worldwide. The Kite Runner was adapted into a graphic novel of the same name in 2011. Hosseini’s much-awaited third novel, And the Mountains Echoed, will be published on May 21, 2013."
  mz = Author.create first_name: "Markus", last_name: "Zusak",photo_id:"http://i854.photobucket.com/albums/ab108/The_Big_Zukini/mzusak_1.jpg", bio: "Markus Zusak was born in 1975 in Sydney, Australia, the youngest of four children of immigrant German and Austrian parents. Neither parent could read or write English when they first arrived in Australia, but they wanted their children to master the language and strongly encouraged them to read and communicate in English from an early age. Zusak began writing fiction at age 16 and pursued a degree in teaching at the University of Sydney. Before becoming a professional author, Zusak worked briefly as a house painter, a janitor and a high school English teacher. The Book Thief followed in 2006 and was met with even more critical and popular success. A sympathetically drawn Death narrates the story of orphan Liesel Meminger, who finds friendship and a new family in a small town in Germany during World War II. She also discovers the power of words and books as Hitler’s Nazi agenda threatens to destroy everything she has come to love. Zusak chose the subject matter in part to share the stories his parents told him about growing up in Austria and Germany during the war. The Book Thief was published as a novel for adults in Australia and as a young adult novel in the United States, but Zusak doesn’t draw such distinctions. “What I wanted to do… was write someone’s favorite book,” rather than write for a specific audience, Zusak revealed in an interview. Author John Green reviewed the book in the New York Times, hailing it as “[b]rilliant” and “achingly sad,” and said of the heroine, “[t]he hope we see in Liesel is unassailable, the kind you can hang on to in the midst of poverty and war and violence."
end


if Book.all.blank?
  Book.create author_id: mx.id, title: "The AutoBiography of Malcom X", photo_id: "http://i854.photobucket.com/albums/ab108/The_Big_Zukini/the-autobiography-of-malcolm-x.jpg", price: "$15"
  Book.create author_id: kh.id, title: "A Thousand Splendid Suns", photo_id: "http://i854.photobucket.com/albums/ab108/The_Big_Zukini/thousandsuns.jpg", price: "$30"
  Book.create author_id: mz.id, title: "The Book Thief", photo_id: "http://i854.photobucket.com/albums/ab108/The_Big_Zukini/book_thief.jpg", price: "$20"
end
